### ISSUE TITLE
Can't install to automatik AMD

### ISSUE THREAD

**Issue by seoeaa** [dustysys/ddetailer#13]
on ubuntu 20.04 worked fine updated put 22.04 now gives out this
`Reloading custom scripts
Error loading script: ddetailer.py
Traceback (most recent call last):
  File "/home/aleks/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/home/aleks/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/home/aleks/stable-diffusion-webui/extensions/ddetailer/scripts/ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "/home/aleks/.local/lib/python3.10/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/aleks/.local/lib/python3.10/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/aleks/.local/lib/python3.10/site-packages/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/aleks/.local/lib/python3.10/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/aleks/.local/lib/python3.10/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/aleks/.local/lib/python3.10/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/aleks/.local/lib/python3.10/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory`

I have an AMD card so I'm not sure if this is necessary.
if you do a search then there is such a file
sudo find / -name 'libcudart.so.11.0'

/home/aleks/.local/lib/python3.10/site-packages/nvidia/cuda_runtime/lib/libcudart.so.11.0

**Comment by lockemx** [comment]
There are unofficial ROCm versions of mmcv. That's probably where you would look to solve this problem anyway.
