### ISSUE TITLE
No module named 'mmengine'

### ISSUE THREAD

**Issue by PompPomp** [dustysys/ddetailer#37]
I am relatively new using AUTOMATIC1111's stable diffusion. I downloaded using the url from the extension, and I had this error:

Error loading script: ddetailer.py
Traceback (most recent call last):
  File "C:\Users\<username>\Desktop\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\<username>\Desktop\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\<username>\Desktop\ai\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "C:\Users\<username>\Desktop\ai\stable-diffusion-webui\venv\lib\site-packages\mmdet\__init__.py", line 3, in <module>
    import mmengine
ModuleNotFoundError: No module named 'mmengine'

**Comment by f4cyw** [comment]
I also same error :(

**Comment by whatifif** [comment]
same error.
I cannot use ddetailer anymore.

**Comment by KorTechTim** [comment]
same error with me 


No module 'xformers'. Proceeding without it.
Error loading script: ddetailer.py
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/ubuntu/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/stable-diffusion-webui/extensions/ddetailer/scripts/ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/mmdet/__init__.py", line 3, in <module>
    import mmengine
ModuleNotFoundError: No module named 'mmengine'



OS : Ubuntu 22.04 LTS
nvidia : Driver Version: 525.105.17
CUDA Version: 12.0
GPU : Nvidia A10

**Comment by fiveseven808** [comment]
Same error. I've manually tried installing mmegine via https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-mim-recommended

I ran 

> pip install -U openmim
> mim install mmcv

and it appears to have worked, but no luck running the SD webui.

**Comment by Tktw** [comment]
Found from the environment in which it was operating.

use `mim install mmdet==2.28.2` on venv.

**Comment by fiveseven808** [comment]
> Found from the environment in which it was operating.
> 
> use `mim install mmdet==2.28.2` on venv.

Could you please assist with this? I am trying to get into venv, but my knowledge on the topic is limited. I try to run the venv\scripts\activate.bat, but it does not put me in the venv environment.

**Comment by GpointChen** [comment]
> > Found from the environment in which it was operating.
> > use `mim install mmdet==2.28.2` on venv.
> 
> Could you please assist with this? I am trying to get into venv, but my knowledge on the topic is limited. I try to run the venv\scripts\activate.bat, but it does not put me in the venv environment.

If you are using Windows, open the command prompt and use the `cd /d` command to navigate to the `venv\Scripts` folder. Once you are in that folder, run the `activate.bat` command. This should put you in the venv and you will be able to run commands such as `python -m pip install mmengine`. It works for me.

**Comment by QuietyAwe** [comment]
I found the problem. I installed it in python on my disk C , and it seems that all I had to do was copy whatever was in the lib folder there to the lib folder in the virtual environment where my webUI use.

**Comment by QuietyAwe** [comment]
ok, now it tells me that _No module named 'mmdet.core'_

**Comment by harkiesvf** [comment]
> 

this worked for me! 
somehow downgrading from mmdet-3.0.0.dist-info to 2.28.2 worked
