### ISSUE TITLE
I can not find it in script.

### ISSUE THREAD

**Issue by QuietyAwe** [dustysys/ddetailer#40]
there are no detection detailer option in script，how can i deal with it？

**Comment by QuietyAwe** [comment]
i find it in my cmd:
_Error loading script: ddetailer.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "D:\stable-diffusion-webui\python\lib\site-packages\mmdet\__init__.py", line 3, in <module>
    import mmengine
ModuleNotFoundError: No module named 'mmengine'_

**Comment by QuietyAwe** [comment]
I run _python -m pip install mmengine_ in venv,but it tells me _No pyvenv.cfg file_,how to deal with it?

**Comment by QuietyAwe** [comment]
I run 
_pip install -U openmim
mim install mmcv_
in venv,it works.
but when i open webUI,it still prints  _ModuleNotFoundError: No module named 'mmengine'_
who can help me ?! TvT

**Comment by QuietyAwe** [comment]
ok, now it tells me that No module named 'mmdet.core'

**Comment by alexcellsinetous** [comment]
> ok, now it tells me that No module named 'mmdet.core'


look at new issues:)
