### ISSUE TITLE
No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by Zullian** [dustysys/ddetailer#50]
This is the error I get, after trying for an hour all the possible combinations I found in resolved issues, still didn't fix it.

![image](https://user-images.githubusercontent.com/3374100/235114457-8aabf38a-5833-4d24-9c8f-1ac6541d5020.png)

Error loading script: ddetailer.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui-master\extensions\ddetailer-master\scripts\ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\~Rocky~\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by FutonGama** [comment]
For me what really fixed after done many tries is. 
pip install --upgrade --force-reinstall mmcv-full

On the end give many errors but worked. And rembg extension gived error also so i removed. The others extensions worked fine and i'm using many extensions.

**Comment by svrakiss** [comment]
see this fork https://github.com/dustysys/ddetailer/pull/54
