### ISSUE TITLE
With the new update to Auto1111, this plugin no longer works.

### ISSUE THREAD

**Issue by fadedninna** [dustysys/ddetailer#53]
As written in the title.

**Comment by lgtaegi** [comment]
same here, I got this error today. any idea?

Launching Web UI with arguments: --xformers --deepdanbooru --autolaunch --no-half-vae
Error loading script: ddetailer.py
Traceback (most recent call last):
  File "J:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "J:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\AI\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "J:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "J:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "J:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "J:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "J:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "J:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "J:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\taegi\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

**Comment by magpie514** [comment]
It's because of the update to Torch 2.x, I believe. Sadly, it's likely it won't work again unless the author decides to come by, or someone forks it.

**Comment by svrakiss** [comment]
> It's because of the update to Torch 2.x, I believe. Sadly, it's likely it won't work again unless the author decides to come by, or someone forks it.

The only mmcv version that supports Torch 2.x is mmcv 2.x (use `mim install mmcv>=2` since they changed the package name from mmcv-full to mmcv ), which forces you to update mmdet to 3.x (`pip install mmdet>=3`), which forces you to port outdated config files to mmdet 3.x and also refactor `inference_mmdet_bbox` and `inference_mmdet_segm`.   I've actually successfully refactored `inference_mmdet_bbox` and the config file for `mmdet_anime-face_yolov3`. For the `from mmdet.core import get_classes` line replace it with `from mmdet.evaluation import get_classes`

**Comment by svrakiss** [comment]
see https://github.com/dustysys/ddetailer/pull/54

**Comment by rafaelfabres** [comment]
Could someone please create a fork of this extension?

**Comment by songib** [comment]
Is this plugin works on AMD guys?
